version = 0.1

[default.deploy.parameters]
stack_name = "fleet-alerts-7"
resolve_s3 = true
s3_prefix = "fleet-alerts-7"
region = "us-east-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "EmailAddress=\"savg215@gmail.com\" Environment=\"prod\""
image_repositories = []
